# -*- coding: utf-8 -*-
"""TC_02_Variable_Advection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1usBmH_8gHcJ3s2KlOjNOsbuK_xAakpm6
"""

# -*- coding: utf-8 -*-
"""
Variable-speed periodic linear advection with learned characteristics

PDE:
    u_t + a(x;beta) u_x = 0,   x in [0,1], t in [0,1]
    a(x;beta) = 1 + beta*sin(2*pi*x),  |beta|<1

BC:
    u(0,t) = u(1,t)

IC:
    u(x,0) = u0(x; x0, nu)
where u0 is a periodic Gaussian bump.

Exact solution:
    Let F_beta(x) = int_0^x dxi / a(xi;beta)
    and P_beta = F_beta(1).
    Then the backward characteristic foot is
        s = F_beta^{-1}( (F_beta(x) - t) mod P_beta )
    and
        u(x,t) = u0(s; x0, nu)

This script trains a learned-characteristic meta-RBF model:
    s = (x - phi_theta(x,t,p)) mod 1,
    p = (x0, nu, beta)

and compares it to the exact solution above.
"""

# ============================================================
# 1) Imports + reproducibility
# ============================================================

import os
import math
import random
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt

SEED = 1234
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

FIG_DIR = "figures_variable_speed_advection"
os.makedirs(FIG_DIR, exist_ok=True)

MODEL_PATH = os.path.join(FIG_DIR, "meta_varspeed_advection_model.pt")

# ============================================================
# 2) Training ranges and utilities
# ============================================================

# Parameters:
#   p = (x0, nu, beta)
#
# x0   : Gaussian center
# nu   : Gaussian width
# beta : variable-speed coefficient in a(x)=1+beta*sin(2*pi*x)

x0_train_range = (0.2, 0.8)
nu_train_range = (0.03, 0.12)
beta_train_range = (0.20, 0.60)

# Easy curriculum on nu: first half trains on smoother bumps only
nu_easy = 0.06

# Domain
X_MIN, X_MAX = 0.0, 1.0
T_FINAL = 1.0

# ============================================================
# 3) Periodic Gaussian + periodic distance
# ============================================================

def periodic_distance_torch(x, y):
    return torch.remainder(x - y + 0.5, 1.0) - 0.5

def periodic_distance_np(x, y):
    return np.remainder(x - y + 0.5, 1.0) - 0.5

def periodic_gaussian(z, mu, nu):
    """
    Periodic wrapped Gaussian centered at mu with width nu.
    """
    if isinstance(z, torch.Tensor):
        d = periodic_distance_torch(z, mu)
        return torch.exp(-d**2 / (2.0 * nu**2))
    else:
        d = periodic_distance_np(z, mu)
        return np.exp(-d**2 / (2.0 * nu**2))

# ============================================================
# 4) Variable-speed field
# ============================================================

def a_of_x_torch(x, beta):
    return 1.0 + beta * torch.sin(2.0 * math.pi * x)

def a_of_x_np(x, beta):
    return 1.0 + beta * np.sin(2.0 * math.pi * x)

# ============================================================
# 5) Exact solution via characteristic travel-time map
# ============================================================

class TravelTimeMap:
    """
    Numerically exact characteristic map for
        dx/dt = a(x;beta) = 1 + beta*sin(2*pi*x),  |beta|<1

    We build:
        F_beta(x) = int_0^x 1/a(xi;beta) dxi
    on a dense grid, then invert by interpolation.

    Exact solution:
        s = F^{-1}( (F(x)-t) mod P )
        u(x,t) = u0(s)
    """
    def __init__(self, beta, n_grid=20001):
        self.beta = float(beta)
        self.n_grid = int(n_grid)

        x = np.linspace(0.0, 1.0, self.n_grid)
        a = a_of_x_np(x, self.beta)

        inv_a = 1.0 / a

        F = np.zeros_like(x)
        dx = x[1] - x[0]
        F[1:] = np.cumsum(0.5 * (inv_a[:-1] + inv_a[1:]) * dx)

        self.x = x
        self.F = F
        self.P = F[-1]

    def forward_F(self, xq):
        """
        F(xq), with xq wrapped into [0,1].
        """
        xq_wrapped = np.mod(xq, 1.0)
        return np.interp(xq_wrapped, self.x, self.F)

    def inverse_F(self, tauq):
        """
        F^{-1}(tauq), where tauq is wrapped into [0,P].
        """
        tau_wrapped = np.mod(tauq, self.P)
        return np.interp(tau_wrapped, self.F, self.x)

def exact_solution_variable_speed(X, T, x0, nu, beta, n_grid_map=20001):
    """
    Exact solution evaluated on arrays X,T of same shape.
    """
    mapper = TravelTimeMap(beta=beta, n_grid=n_grid_map)

    Fx = mapper.forward_F(X)
    tau0 = np.mod(Fx - T, mapper.P)
    s = mapper.inverse_F(tau0)

    return periodic_gaussian(s, x0, nu)

# ============================================================
# 6) Learned-characteristic Meta-RBF model
# ============================================================

class MetaKAPIRBF_VarSpeedAdvection(nn.Module):
    """
    p = (x0, nu, beta)

    Learned characteristic coordinate:
        s = (x - phi_theta(x,t,p)) mod 1

    Meta-network outputs RBF parameters in s-space:
        g_j, s_center_j, sigma_j, coeff_j

    RBF representation:
        u = sum_j (g_j * coeff_j) exp( - d_per(s,s_j)^2 / sigma_j^2 )
    """
    def __init__(self, M=64, hidden_meta=64, hidden_char=64):
        super().__init__()
        self.M = M

        # Meta-network for RBF dictionary parameters
        self.meta = nn.Sequential(
            nn.Linear(3, hidden_meta),
            nn.Tanh(),
            nn.Linear(hidden_meta, hidden_meta),
            nn.Tanh(),
            nn.Linear(hidden_meta, 4 * M)
        )

        # Characteristic map network
        # Inputs use periodic x-encoding: [sin(2pi x), cos(2pi x), t, normalized p]
        self.char_net = nn.Sequential(
            nn.Linear(2 + 1 + 3, hidden_char),  # sinx, cosx, t, x0,nu,beta
            nn.Tanh(),
            nn.Linear(hidden_char, hidden_char),
            nn.Tanh(),
            nn.Linear(hidden_char, 1)
        )

    def normalize_p(self, p):
        # p = (x0, nu, beta)
        p_mean = p.new_tensor([0.5, 0.075, 0.40])
        p_std  = p.new_tensor([0.3, 0.03, 0.15])
        return (p - p_mean) / p_std

    def forward(self, p, xt):
        """
        p  : (B,3)
        xt : (B,N,2)

        returns:
            u   : (B,N)
            aux : tuple for diagnostics
        """
        B, N, _ = xt.shape

        p_norm = self.normalize_p(p)

        # -----------------------------------
        # Learned characteristic displacement
        # -----------------------------------
        x = xt[:, :, 0]
        t = xt[:, :, 1]

        sinx = torch.sin(2.0 * math.pi * x)
        cosx = torch.cos(2.0 * math.pi * x)

        p_rep = p_norm.unsqueeze(1).expand(B, N, 3)

        char_in = torch.cat([
            sinx.unsqueeze(-1),
            cosx.unsqueeze(-1),
            t.unsqueeze(-1),
            p_rep
        ], dim=-1)

        phi_raw = self.char_net(char_in.reshape(B * N, -1)).reshape(B, N)

        # Enforce phi(x,0,p)=0 by multiplying by t
        # Bound displacement magnitude moderately for stability
        phi = t * (1.25 * torch.tanh(phi_raw))

        s = torch.remainder(x - phi, 1.0)

        # -----------------------------------
        # Meta-network for RBF parameters
        # -----------------------------------
        meta_out = self.meta(p_norm).view(B, 4, self.M)

        g_logits  = meta_out[:, 0, :]
        s_raw     = meta_out[:, 1, :]
        log_sigr  = meta_out[:, 2, :]
        coeff_raw = meta_out[:, 3, :]

        g = torch.sigmoid(g_logits)
        s_centers = torch.sigmoid(s_raw)
        sigma = torch.nn.functional.softplus(log_sigr) + 1e-3
        coeff = torch.tanh(coeff_raw)

        # -----------------------------------
        # RBF evaluation on periodic s-domain
        # -----------------------------------
        s_exp = s.unsqueeze(-1)                    # (B,N,1)
        s_cent_exp = s_centers.unsqueeze(1)       # (B,1,M)
        sigma_exp = sigma.unsqueeze(1)            # (B,1,M)
        g_exp = g.unsqueeze(1)                    # (B,1,M)
        coeff_exp = coeff.unsqueeze(1)            # (B,1,M)

        d = torch.remainder(s_exp - s_cent_exp + 0.5, 1.0) - 0.5
        r2 = d**2 / (sigma_exp**2)
        Phi = torch.exp(-r2)

        u = torch.sum(Phi * (g_exp * coeff_exp), dim=-1)

        return u, (g, s_centers, sigma, coeff, phi, s)

# ============================================================
# 7) Sampling utilities
# ============================================================

def sample_p_batch(B,
                   x0_range=x0_train_range,
                   nu_range=nu_train_range,
                   beta_range=beta_train_range):
    """
    Sample p=(x0,nu,beta).
    nu is sampled log-uniformly.
    """
    x0 = x0_range[0] + (x0_range[1] - x0_range[0]) * torch.rand(B, 1)

    u_rand = torch.rand(B, 1)
    nu_min, nu_max = nu_range
    nu = 10 ** (
        torch.log10(torch.tensor([nu_min])) +
        (torch.log10(torch.tensor([nu_max])) - torch.log10(torch.tensor([nu_min]))) * u_rand
    )

    beta = beta_range[0] + (beta_range[1] - beta_range[0]) * torch.rand(B, 1)

    return torch.cat([x0, nu, beta], dim=1).to(device)

def sample_interior_points_batch(B, N_int):
    x = torch.rand(B, N_int, 1)
    t = torch.rand(B, N_int, 1)
    return torch.cat([x, t], dim=2).to(device)

def sample_ic_points_batch(B, N_ic):
    x = torch.rand(B, N_ic, 1)
    t = torch.zeros(B, N_ic, 1)
    return torch.cat([x, t], dim=2).to(device)

def sample_periodic_points_batch(B, N_per):
    t = torch.rand(B, N_per, 1)
    xL = torch.zeros(B, N_per, 1)
    xR = torch.ones(B, N_per, 1)
    return torch.cat([xL, t], dim=2).to(device), torch.cat([xR, t], dim=2).to(device)

# ============================================================
# 8) PDE residual: u_t + a(x;beta) u_x
# ============================================================

def advection_residual_batch(model, p, xt_int):
    """
    p      : (B,3) = (x0,nu,beta)
    xt_int : (B,N,2)

    returns:
        residual : (B,N)
    """
    xt_req = xt_int.clone().detach().requires_grad_(True)

    u, _ = model(p, xt_req)

    grad_u = torch.autograd.grad(
        outputs=u,
        inputs=xt_req,
        grad_outputs=torch.ones_like(u),
        create_graph=True
    )[0]

    u_x = grad_u[:, :, 0]
    u_t = grad_u[:, :, 1]

    x = xt_req[:, :, 0]
    beta = p[:, 2:3].expand_as(x)

    a = a_of_x_torch(x, beta)

    return u_t + a * u_x

# ============================================================
# 9) Training
# ============================================================

def train_meta_varspeed_advection(
    B_pde=8,
    N_int=512,
    N_ic=256,
    N_per=256,
    epochs=5000,
    lr=5e-4,
    M=64,
    hidden_meta=64,
    hidden_char=64,
    w_sparse=1e-4,
    w_warp=1e-5
):
    model = MetaKAPIRBF_VarSpeedAdvection(
        M=M,
        hidden_meta=hidden_meta,
        hidden_char=hidden_char
    ).to(device)

    optimizer = optim.Adam(model.parameters(), lr=lr)

    best_loss = float("inf")
    best_state = None

    history = {
        "epoch": [],
        "total_loss": [],
        "loss_pde": [],
        "loss_ic": [],
        "loss_per": [],
        "loss_sparse": [],
        "loss_warp": []
    }

    for ep in range(1, epochs + 1):
        optimizer.zero_grad()

        # Curriculum on nu only
        if ep <= epochs // 2:
            nu_min_curr, nu_max_curr = nu_easy, nu_train_range[1]
        else:
            nu_min_curr, nu_max_curr = nu_train_range

        p_batch = sample_p_batch(
            B_pde,
            x0_range=x0_train_range,
            nu_range=(nu_min_curr, nu_max_curr),
            beta_range=beta_train_range
        )

        xt_int = sample_interior_points_batch(B_pde, N_int)
        xt_ic  = sample_ic_points_batch(B_pde, N_ic)
        xtL, xtR = sample_periodic_points_batch(B_pde, N_per)

        # PDE residual
        res_int = advection_residual_batch(model, p_batch, xt_int)
        loss_pde = torch.mean(res_int**2)

        # IC loss
        u_ic, _ = model(p_batch, xt_ic)
        x_ic = xt_ic[:, :, 0]
        x0 = p_batch[:, 0:1].expand_as(x_ic)
        nu = p_batch[:, 1:2].expand_as(x_ic)

        u_ic_exact = periodic_gaussian(x_ic, x0, nu)
        loss_ic = torch.mean((u_ic - u_ic_exact)**2)

        # Periodic BC
        uL, _ = model(p_batch, xtL)
        uR, _ = model(p_batch, xtR)
        loss_per = torch.mean((uL - uR)**2)

        # Sparsity on gates
        _, (g, _, _, _, _, _) = model(p_batch, sample_interior_points_batch(B_pde, 64))
        loss_sparse = w_sparse * torch.mean(torch.abs(g))

        # Mild warp regularization
        _, (_, _, _, _, phi_reg, _) = model(p_batch, sample_interior_points_batch(B_pde, 64))
        loss_warp = w_warp * torch.mean(phi_reg**2)

        loss = loss_pde + loss_ic + loss_per + loss_sparse + loss_warp

        loss.backward()
        optimizer.step()

        history["epoch"].append(ep)
        history["total_loss"].append(loss.item())
        history["loss_pde"].append(loss_pde.item())
        history["loss_ic"].append(loss_ic.item())
        history["loss_per"].append(loss_per.item())
        history["loss_sparse"].append(loss_sparse.item())
        history["loss_warp"].append(loss_warp.item())

        if loss.item() < best_loss:
            best_loss = loss.item()
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}

        if ep % 200 == 0:
            print(
                f"Epoch {ep:4d} | Loss={loss.item():.3e} "
                f"| PDE={loss_pde.item():.3e} "
                f"| IC={loss_ic.item():.3e} "
                f"| PER={loss_per.item():.3e} "
                f"| nu-range=[{nu_min_curr:.3f},{nu_max_curr:.3f}]"
            )

    print(f"\nBest loss = {best_loss:.3e}")
    model.load_state_dict({k: v.to(device) for k, v in best_state.items()})

    return model, history

# ============================================================
# 10) Training curve
# ============================================================

def plot_training_curve(history):
    plt.figure(figsize=(6, 4))
    plt.plot(history["epoch"], history["total_loss"], label="total")
    plt.plot(history["epoch"], history["loss_pde"], label="pde", alpha=0.8)
    plt.plot(history["epoch"], history["loss_ic"], label="ic", alpha=0.8)
    plt.yscale("log")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.grid(True)
    plt.legend()
    plt.title("Variable-speed advection training loss")
    plt.tight_layout()

    path = os.path.join(FIG_DIR, "training_curve.png")
    plt.savefig(path, dpi=300)
    plt.show()
    print("Saved:", path)

# ============================================================
# 11) Evaluation and plotting against exact solution
# ============================================================

def evaluate_and_plot_varspeed(model, test_cases, Nx=220, Nt=220, map_grid=20001):
    """
    test_cases: list of tuples
        (name, x0_test, nu_test, beta_test)

    Layout:
        columns = test cases
        rows    = [Exact, KAPI, |u_KAPI-u_Exact|]
    """
    num_tests = len(test_cases)

    fig, axs = plt.subplots(
        3, num_tests,
        figsize=(4.2 * num_tests, 9.5),
        constrained_layout=True
    )

    if num_tests == 1:
        axs = axs.reshape(3, 1)

    rel_errors = []

    x = np.linspace(0.0, 1.0, Nx)
    t = np.linspace(0.0, 1.0, Nt)
    X, T = np.meshgrid(x, t, indexing='ij')

    xt_grid = np.stack([X.ravel(), T.ravel()], axis=1)
    xt_grid_t = torch.tensor(xt_grid, dtype=torch.float32, device=device).view(1, -1, 2)

    model.eval()

    exact_list = []
    pred_list = []
    err_list = []

    for i, (_, x0_test, nu_test, beta_test) in enumerate(test_cases):
        print(f"\nTest case {i+1}, p=({x0_test}, {nu_test}, {beta_test})")

        p_test = torch.tensor([[x0_test, nu_test, beta_test]], dtype=torch.float32, device=device)

        with torch.no_grad():
            pred_flat, _ = model(p_test, xt_grid_t)
        u_pred = pred_flat.cpu().numpy().reshape(Nx, Nt)

        u_exact = exact_solution_variable_speed(X, T, x0_test, nu_test, beta_test, n_grid_map=map_grid)
        u_err = np.abs(u_pred - u_exact)

        rel_L2 = np.linalg.norm((u_pred - u_exact).ravel()) / (np.linalg.norm(u_exact.ravel()) + 1e-12)
        rel_errors.append((i + 1, rel_L2))
        print(f"Relative L2 = {rel_L2:.3e}")

        exact_list.append((x0_test, nu_test, beta_test, u_exact))
        pred_list.append((x0_test, nu_test, beta_test, u_pred))
        err_list.append((x0_test, nu_test, beta_test, u_err))

    # Shared color limits
    all_sol_vals = np.concatenate([u.ravel() for _, _, _, u in exact_list + pred_list])
    sol_vmin = np.min(all_sol_vals)
    sol_vmax = np.max(all_sol_vals)

    all_err_vals = np.concatenate([u.ravel() for _, _, _, u in err_list])
    err_vmin = 0.0
    err_vmax = np.max(all_err_vals)

    im_sol = None
    im_err = None

    for j in range(num_tests):
        x0_test, nu_test, beta_test, u_exact = exact_list[j]
        _, _, _, u_pred = pred_list[j]
        _, _, _, u_err = err_list[j]

        # Row 1: Exact
        ax = axs[0, j]
        im_sol = ax.imshow(
            u_exact.T,
            origin='lower',
            extent=[0, 1, 0, 1],
            aspect='auto',
            vmin=sol_vmin,
            vmax=sol_vmax
        )
        ax.set_title(rf"$(x_0,\nu,\beta)=({x0_test:.2f},{nu_test:.2f},{beta_test:.2f})$", fontsize=14)
        ax.set_xlabel("x")
        if j == 0:
            ax.set_ylabel("Exact", fontsize=13)

        # Row 2: KAPI
        ax = axs[1, j]
        ax.imshow(
            u_pred.T,
            origin='lower',
            extent=[0, 1, 0, 1],
            aspect='auto',
            vmin=sol_vmin,
            vmax=sol_vmax
        )
        ax.set_xlabel("x")
        if j == 0:
            ax.set_ylabel("KAPI", fontsize=13)

        # Row 3: Error
        ax = axs[2, j]
        im_err = ax.imshow(
            u_err.T,
            origin='lower',
            extent=[0, 1, 0, 1],
            aspect='auto',
            vmin=err_vmin,
            vmax=err_vmax
        )
        ax.set_xlabel("x")
        if j == 0:
            ax.set_ylabel(r"$|u_{\mathrm{KAPI}}-u_{\mathrm{Exact}}|$", fontsize=13)

    # Two colorbars only
    cbar1 = fig.colorbar(im_sol, ax=axs[0:2, :], shrink=0.95, location='right')
    cbar1.set_label("Solution value", fontsize=12)

    cbar2 = fig.colorbar(im_err, ax=axs[2, :], shrink=0.95, location='right')
    cbar2.set_label("Absolute error", fontsize=12)

    # Training ranges at the bottom of the full figure
    training_text = (
        rf"Training ranges: "
        rf"$x_0 \in [{x0_train_range[0]:.2f},{x0_train_range[1]:.2f}]$, "
        rf"$\nu \in [{nu_train_range[0]:.2f},{nu_train_range[1]:.2f}]$, "
        rf"$\beta \in [{beta_train_range[0]:.2f},{beta_train_range[1]:.2f}]$"
    )

    fig.text(
        0.5, -0.02,
        training_text,
        ha='center',
        va='top',
        fontsize=13
    )

    combined_path = os.path.join(FIG_DIR, "varspeed_meta_results_clean.png")
    plt.savefig(combined_path, dpi=300, bbox_inches='tight')
    plt.show()
    print(f"\nSaved combined results -> {combined_path}")

    print("\nSummary of relative L2 errors:")
    for idx, e in rel_errors:
        print(f"  Test case {idx:2d}: {e:.3e}")

# ============================================================
# 12) Diagnostic: visualize learned characteristic map
# ============================================================

def visualize_learned_map(model, x0_test, nu_test, beta_test, Nx=240, Nt=160):
    """
    Visualize learned characteristic foot-coordinate s(x,t).
    """
    x = np.linspace(0.0, 1.0, Nx)
    t = np.linspace(0.0, 1.0, Nt)
    X, T = np.meshgrid(x, t, indexing='ij')

    xt_grid = np.stack([X.ravel(), T.ravel()], axis=1)
    xt_grid_t = torch.tensor(xt_grid, dtype=torch.float32, device=device).view(1, -1, 2)

    p_test = torch.tensor([[x0_test, nu_test, beta_test]], dtype=torch.float32, device=device)

    with torch.no_grad():
        _, (_, _, _, _, phi, s) = model(p_test, xt_grid_t)

    phi_np = phi.view(Nx, Nt).cpu().numpy()
    s_np = s.view(Nx, Nt).cpu().numpy()

    plt.figure(figsize=(12, 4))

    plt.subplot(1, 2, 1)
    plt.imshow(phi_np.T, origin='lower', extent=[0, 1, 0, 1], aspect='auto')
    plt.xlabel("x")
    plt.ylabel("t")
    plt.title("Learned displacement phi(x,t,p)")
    plt.colorbar()

    plt.subplot(1, 2, 2)
    plt.imshow(s_np.T, origin='lower', extent=[0, 1, 0, 1], aspect='auto')
    plt.xlabel("x")
    plt.ylabel("t")
    plt.title("Learned characteristic coordinate s(x,t,p)")
    plt.colorbar()

    plt.tight_layout()
    path = os.path.join(FIG_DIR, "learned_map_diagnostic.png")
    plt.savefig(path, dpi=300)
    plt.show()
    print("Saved:", path)

# ============================================================
# 13) Main: train -> save -> reload -> evaluate
# ============================================================

if __name__ == "__main__":

    model, history = train_meta_varspeed_advection(
        B_pde=8,
        N_int=512,
        N_ic=256,
        N_per=256,
        epochs=5000,
        lr=5e-4,
        M=64,
        hidden_meta=64,
        hidden_char=64,
        w_sparse=1e-4,
        w_warp=1e-5
    )

    torch.save(model.state_dict(), MODEL_PATH)
    print("Saved model to:", MODEL_PATH)

    plot_training_curve(history)

    loaded_model = MetaKAPIRBF_VarSpeedAdvection(M=64, hidden_meta=64, hidden_char=64).to(device)
    loaded_model.load_state_dict(torch.load(MODEL_PATH, map_location=device))
    loaded_model.eval()
    print("Reloaded model.")

    # In-range and mild out-of-range tests
    test_cases = [
        ("center_in_range",        0.50, 0.07, 0.35),
        ("off_center_in_range",    0.30, 0.09, 0.55),
        ("narrow_in_range",        0.65, 0.04, 0.45),
        ("narrow_beta_out_range",  0.50, 0.04, 0.70),
    ]

    evaluate_and_plot_varspeed(
        loaded_model,
        test_cases=test_cases,
        Nx=220,
        Nt=220,
        map_grid=20001
    )

    visualize_learned_map(
        loaded_model,
        x0_test=0.50,
        nu_test=0.07,
        beta_test=0.55,
        Nx=240,
        Nt=160
    )