# -*- coding: utf-8 -*-
"""TC_02_Advection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sAGNJKOd8d9OqH_c6pCwNFrtaz4F3BgM
"""

# ============================================================
# META-KAPI-RBF for Linear Advection
# Learned-characteristic version
#
# Characteristic-informed benchmark:
#     s = (x - t) mod 1
#
# Learned-characteristic version:
#     s = (x - v(p)*t) mod 1
#
# where v(p) is predicted by a small neural network.
#
# Memory-safe version:
#   - avoids repeating p for every collocation point
#   - computes PDE residual in batched form
#   - uses periodic distance in learned RBFs
#   - includes multi-case meta-learning evaluation plots
# ============================================================

import os
import csv
import random
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt

# ------------------------------
# Reproducibility
# ------------------------------
SEED = 1234
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

FIG_DIR = "figures_advection_learned_char"
os.makedirs(FIG_DIR, exist_ok=True)

MODEL_PATH = "meta_advection_learned_char.pt"

nu_min, nu_max = 0.03, 0.12
nu_easy = 0.06

# ============================================================
# Periodic Gaussian
# ============================================================

def periodic_gaussian(z, mu, nu):
    """
    Periodic Gaussian on [0,1).
    Supports both torch tensors and numpy arrays.
    """
    if isinstance(z, torch.Tensor):
        d = torch.remainder(z - mu + 0.5, 1.0) - 0.5
        return torch.exp(-(d ** 2) / (2.0 * nu ** 2))
    else:
        d = np.remainder(z - mu + 0.5, 1.0) - 0.5
        return np.exp(-(d ** 2) / (2.0 * nu ** 2))

# ============================================================
# Learned-characteristic Meta-KAPI-RBF
# ============================================================

class MetaKAPIRBF_Advection(nn.Module):
    def __init__(self, M=32, hidden_meta=64, hidden_speed=32):
        super().__init__()

        self.M = M

        # Meta-network producing RBF parameters
        self.meta = nn.Sequential(
            nn.Linear(2, hidden_meta),
            nn.Tanh(),
            nn.Linear(hidden_meta, hidden_meta),
            nn.Tanh(),
            nn.Linear(hidden_meta, 4 * M)
        )

        # Small network for characteristic speed
        self.speed_net = nn.Sequential(
            nn.Linear(2, hidden_speed),
            nn.Tanh(),
            nn.Linear(hidden_speed, hidden_speed),
            nn.Tanh(),
            nn.Linear(hidden_speed, 1)
        )

    def forward(self, p, xt):
        """
        Inputs:
            p  : (B, 2)      -> parameters [x0, nu]
            xt : (B, N, 2)   -> collocation/query points [x, t]

        Outputs:
            u  : (B, N)
            aux: tuple (g, s_centers, sigma, coeff, v)
        """
        B, N, _ = xt.shape

        # -----------------------------------
        # Normalize parameters
        # -----------------------------------
        p_mean = p.new_tensor([0.5, 0.075])
        p_std  = p.new_tensor([0.3, 0.03])
        p_norm = (p - p_mean) / p_std

        # -----------------------------------
        # Learned characteristic speed
        # -----------------------------------
        v = self.speed_net(p_norm)            # (B,1)
        v = 1.0 + 0.2 * torch.tanh(v)         # keep speed near 1

        # -----------------------------------
        # Meta-network
        # -----------------------------------
        meta_out = self.meta(p_norm).view(B, 4, self.M)

        g_logits  = meta_out[:, 0, :]
        s_raw     = meta_out[:, 1, :]
        log_sigma = meta_out[:, 2, :]
        coeff_raw = meta_out[:, 3, :]

        g = torch.sigmoid(g_logits)                             # (B,M)
        s_centers = torch.sigmoid(s_raw)                        # (B,M)
        sigma = torch.nn.functional.softplus(log_sigma) + 1e-3 # (B,M)
        coeff = torch.tanh(coeff_raw)                           # (B,M)

        # -----------------------------------
        # Characteristic coordinate
        # -----------------------------------
        x = xt[:, :, 0]   # (B,N)
        t = xt[:, :, 1]   # (B,N)

        s = torch.remainder(x - v * t, 1.0)  # (B,N)

        # -----------------------------------
        # Periodic RBF evaluation
        # -----------------------------------
        s_exp = s.unsqueeze(-1)               # (B,N,1)
        s_cent_exp = s_centers.unsqueeze(1)   # (B,1,M)
        sigma_exp = sigma.unsqueeze(1)        # (B,1,M)
        g_exp = g.unsqueeze(1)                # (B,1,M)
        coeff_exp = coeff.unsqueeze(1)        # (B,1,M)

        d = torch.remainder(s_exp - s_cent_exp + 0.5, 1.0) - 0.5
        r2 = d ** 2 / (sigma_exp ** 2)

        Phi = torch.exp(-r2)                  # (B,N,M)
        u = torch.sum(Phi * (g_exp * coeff_exp), dim=-1)  # (B,N)

        return u, (g, s_centers, sigma, coeff, v)

# ============================================================
# Sampling utilities
# ============================================================

def sample_p_batch(B, x0_range=(0.2, 0.8), nu_range=(0.03, 0.12)):
    """
    Sample parameter batch:
        p = [x0, nu]
    with log-uniform sampling in nu.
    """
    x0 = x0_range[0] + (x0_range[1] - x0_range[0]) * torch.rand(B, 1)

    u_rand = torch.rand(B, 1)

    nu_min_loc, nu_max_loc = nu_range
    log_nu_min = np.log10(nu_min_loc)
    log_nu_max = np.log10(nu_max_loc)

    nu = 10 ** (log_nu_min + (log_nu_max - log_nu_min) * u_rand)

    return torch.cat([x0, nu], dim=1).to(device)

def sample_interior_points_batch(B, N):
    x = torch.rand(B, N, 1)
    t = torch.rand(B, N, 1)
    return torch.cat([x, t], dim=2).to(device)

def sample_ic_points_batch(B, N):
    x = torch.rand(B, N, 1)
    t = torch.zeros(B, N, 1)
    return torch.cat([x, t], dim=2).to(device)

def sample_periodic_points_batch(B, N):
    t = torch.rand(B, N, 1)

    xL = torch.zeros(B, N, 1)
    xR = torch.ones(B, N, 1)

    xtL = torch.cat([xL, t], dim=2).to(device)
    xtR = torch.cat([xR, t], dim=2).to(device)

    return xtL, xtR

# ============================================================
# PDE residual
# ============================================================

def advection_residual_batch(model, p, xt_int):
    """
    Computes PDE residual for u_t + u_x = 0 in batched form.

    Inputs:
        p      : (B,2)
        xt_int : (B,N,2)

    Returns:
        residual : (B,N)
    """
    xt_int = xt_int.clone().detach().requires_grad_(True)

    u, _ = model(p, xt_int)   # (B,N)

    grads = torch.autograd.grad(
        outputs=u,
        inputs=xt_int,
        grad_outputs=torch.ones_like(u),
        create_graph=True,
        retain_graph=True
    )[0]  # (B,N,2)

    u_x = grads[:, :, 0]
    u_t = grads[:, :, 1]

    return u_t + u_x

# ============================================================
# Plot / evaluation utilities
# ============================================================

def plot_training_history(history, save_path):
    plt.figure(figsize=(7, 4.5))
    plt.plot(history["epoch"], history["loss"], lw=2, label="Total")
    plt.plot(history["epoch"], history["loss_pde"], lw=1.5, label="PDE")
    plt.plot(history["epoch"], history["loss_ic"], lw=1.5, label="IC")
    plt.plot(history["epoch"], history["loss_per"], lw=1.5, label="Periodic BC")
    plt.yscale("log")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.title("Training Loss History")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(save_path, dpi=300)
    plt.close()

def evaluate_exact_solution(x, t, x0, nu, speed=1.0):
    """
    Exact solution for periodic linear advection:
        u_t + speed*u_x = 0
    Here the true speed is 1.
    """
    s = np.remainder(x - speed * t, 1.0)
    return periodic_gaussian(s, x0, nu)

def plot_solution_snapshot(model, x0, nu, t_snap=0.5, nx=400, save_path=None):
    model.eval()

    x = np.linspace(0.0, 1.0, nx, endpoint=False)
    t = t_snap * np.ones_like(x)

    xt = np.stack([x, t], axis=1)[None, :, :]
    p = np.array([[x0, nu]], dtype=np.float32)

    xt_torch = torch.tensor(xt, dtype=torch.float32, device=device)
    p_torch = torch.tensor(p, dtype=torch.float32, device=device)

    with torch.no_grad():
        u_pred, (_, _, _, _, v_pred) = model(p_torch, xt_torch)

    u_pred = u_pred[0].cpu().numpy()
    v_pred = float(v_pred.item())
    u_exact = evaluate_exact_solution(x, t, x0, nu)

    plt.figure(figsize=(7, 4))
    plt.plot(x, u_exact, lw=2, label="Exact")
    plt.plot(x, u_pred, "--", lw=2, label="Prediction")
    plt.xlabel("x")
    plt.ylabel("u(x,t)")
    plt.title(f"Snapshot at t={t_snap:.2f}, x0={x0:.3f}, nu={nu:.3f}, v_pred={v_pred:.4f}")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()

    if save_path is not None:
        plt.savefig(save_path, dpi=300)
        plt.close()
    else:
        plt.show()

def evaluate_case_on_grid(model, x0_test, nu_test, Nx=200, Nt=200):
    """
    Evaluate one test case on a full (x,t) grid.
    """
    x = np.linspace(0.0, 1.0, Nx, endpoint=False)
    t = np.linspace(0.0, 1.0, Nt)
    X, T = np.meshgrid(x, t, indexing="ij")

    xt_grid = np.stack([X.ravel(), T.ravel()], axis=1)
    xt_grid_t = torch.tensor(xt_grid, dtype=torch.float32, device=device).view(1, -1, 2)

    p_test = torch.tensor([[x0_test, nu_test]], dtype=torch.float32, device=device)

    model.eval()
    with torch.no_grad():
        u_pred_flat, (_, _, _, _, v_pred) = model(p_test, xt_grid_t)

    u_pred = u_pred_flat.cpu().numpy().reshape(Nx, Nt)
    v_pred_scalar = float(v_pred.item())

    u_exact = evaluate_exact_solution(X, T, x0_test, nu_test, speed=1.0)
    abs_err = np.abs(u_pred - u_exact)
    rel_l2 = np.linalg.norm((u_pred - u_exact).ravel()) / (np.linalg.norm(u_exact.ravel()) + 1e-14)

    return {
        "x": x,
        "t": t,
        "X": X,
        "T": T,
        "u_exact": u_exact,
        "u_pred": u_pred,
        "abs_err": abs_err,
        "rel_l2": rel_l2,
        "v_pred": v_pred_scalar,
    }

def plot_multicase_fields(model, test_cases, Nx=200, Nt=200, save_dir=FIG_DIR):
    """
    Combined multi-case figure in the style:
        columns = test cases
        rows    = [Exact, KAPI, |u_KAPI-u_Exact|]

    Titles only show (x0, nu).
    """
    num_tests = len(test_cases)

    fig, axs = plt.subplots(
        3, num_tests,
        figsize=(4.4 * num_tests, 9.6),
        constrained_layout=True
    )

    if num_tests == 1:
        axs = axs.reshape(3, 1)

    summary = []
    exact_list = []
    pred_list = []
    err_list = []

    for i, (name, x0_test, nu_test) in enumerate(test_cases):
        result = evaluate_case_on_grid(model, x0_test, nu_test, Nx=Nx, Nt=Nt)

        u_exact = result["u_exact"]
        u_pred  = result["u_pred"]
        abs_err = result["abs_err"]
        rel_l2  = result["rel_l2"]
        v_pred  = result["v_pred"]

        summary.append({
            "name": name,
            "x0": x0_test,
            "nu": nu_test,
            "rel_l2": rel_l2,
            "v_pred": v_pred,
            "speed_error": abs(v_pred - 1.0),
        })

        exact_list.append((x0_test, nu_test, u_exact))
        pred_list.append((x0_test, nu_test, u_pred))
        err_list.append((x0_test, nu_test, abs_err))

    # Shared color limits
    all_sol_vals = np.concatenate([u.ravel() for _, _, u in exact_list + pred_list])
    sol_vmin = np.min(all_sol_vals)
    sol_vmax = np.max(all_sol_vals)

    all_err_vals = np.concatenate([u.ravel() for _, _, u in err_list])
    err_vmin = 0.0
    err_vmax = np.max(all_err_vals)

    im_sol = None
    im_err = None

    for j in range(num_tests):

        x0_test, nu_test, u_exact = exact_list[j]
        _, _, u_pred = pred_list[j]
        _, _, abs_err = err_list[j]

        # Row 1: Exact
        ax = axs[0, j]
        im_sol = ax.imshow(
            u_exact.T,
            origin="lower",
            extent=[0, 1, 0, 1],
            aspect="auto",
            vmin=sol_vmin,
            vmax=sol_vmax
        )
        ax.set_title(rf"$(x_0,\nu)=({x0_test:.2f},{nu_test:.2f})$", fontsize=14)
        ax.set_xlabel("x")
        if j == 0:
            ax.set_ylabel("Exact", fontsize=13)

        # Row 2: Prediction
        ax = axs[1, j]
        ax.imshow(
            u_pred.T,
            origin="lower",
            extent=[0, 1, 0, 1],
            aspect="auto",
            vmin=sol_vmin,
            vmax=sol_vmax
        )
        ax.set_xlabel("x")
        if j == 0:
            ax.set_ylabel("KAPI", fontsize=13)

        # Row 3: Error
        ax = axs[2, j]
        im_err = ax.imshow(
            abs_err.T,
            origin="lower",
            extent=[0, 1, 0, 1],
            aspect="auto",
            vmin=err_vmin,
            vmax=err_vmax
        )
        ax.set_xlabel("x")
        if j == 0:
            ax.set_ylabel(r"$|u_{\mathrm{KAPI}}-u_{\mathrm{Exact}}|$", fontsize=13)

    # Shared colorbars
    cbar1 = fig.colorbar(im_sol, ax=axs[0:2, :], shrink=0.95, location="right")
    cbar1.set_label("Solution value", fontsize=12)

    cbar2 = fig.colorbar(im_err, ax=axs[2, :], shrink=0.95, location="right")
    cbar2.set_label("Absolute error", fontsize=12)

    # Training range annotation
    training_text = (
        rf"Training ranges: "
        rf"$x_0 \in [0.20,0.80]$, "
        rf"$\nu \in [{nu_min:.2f},{nu_max:.2f}]$"
    )

    fig.text(
        0.5, -0.02,
        training_text,
        ha="center",
        va="top",
        fontsize=13
    )

    combined_path = os.path.join(save_dir, "multicase_fields.png")
    fig.savefig(combined_path, dpi=300, bbox_inches="tight")
    plt.close(fig)

    print(f"Saved combined multicase field plot -> {combined_path}")

    return summary

def plot_time_slices(model, test_cases, t_slices=(0.0, 0.25, 0.50, 0.75, 1.0), Nx=400, save_dir=FIG_DIR):
    """
    For each test case, compare exact and predicted solution at multiple time slices.
    """
    x = np.linspace(0.0, 1.0, Nx, endpoint=False)

    for name, x0_test, nu_test in test_cases:
        fig, axs = plt.subplots(1, len(t_slices), figsize=(4 * len(t_slices), 3.8), constrained_layout=True)
        if len(t_slices) == 1:
            axs = [axs]

        p_test = torch.tensor([[x0_test, nu_test]], dtype=torch.float32, device=device)

        model.eval()
        learned_v = None

        for k, t_val in enumerate(t_slices):
            xt = np.stack([x, t_val * np.ones_like(x)], axis=1)[None, :, :]
            xt_t = torch.tensor(xt, dtype=torch.float32, device=device)

            with torch.no_grad():
                u_pred, (_, _, _, _, v_pred) = model(p_test, xt_t)

            u_pred = u_pred[0].cpu().numpy()
            u_exact = evaluate_exact_solution(x, t_val, x0_test, nu_test, speed=1.0)

            if learned_v is None:
                learned_v = float(v_pred.item())

            ax = axs[k]
            ax.plot(x, u_exact, lw=2, label="Exact")
            ax.plot(x, u_pred, "--", lw=2, label="Prediction")
            ax.set_title(f"t = {t_val:.2f}")
            ax.set_xlabel("x")
            ax.set_ylabel("u")
            ax.grid(True, alpha=0.3)
            if k == 0:
                ax.legend()

        fig.suptitle(
            f"Time-slice comparison: {name} | x0={x0_test:.3f}, nu={nu_test:.3f}, v_pred={learned_v:.4f}",
            fontsize=13
        )

        save_path = os.path.join(save_dir, f"time_slices_{name}.png")
        fig.savefig(save_path, dpi=300)
        plt.close(fig)
        print(f"Saved time-slice figure -> {save_path}")

def plot_error_summary(summary, save_dir=FIG_DIR):
    names = [item["name"] for item in summary]
    rel_l2 = [item["rel_l2"] for item in summary]

    fig_path = os.path.join(save_dir, "error_summary.png")

    plt.figure(figsize=(8, 4))
    plt.bar(names, rel_l2)
    plt.yscale("log")
    plt.ylabel("Relative L2 Error")
    plt.title("Meta-learning Generalization Across Test Cases")
    plt.xticks(rotation=25, ha="right")
    plt.grid(True, alpha=0.3, axis="y")
    plt.tight_layout()
    plt.savefig(fig_path, dpi=300)
    plt.close()

    print(f"Saved error summary -> {fig_path}")

def plot_speed_summary(summary, save_dir=FIG_DIR):
    names = [item["name"] for item in summary]
    vvals = [item["v_pred"] for item in summary]

    fig_path = os.path.join(save_dir, "speed_summary.png")

    plt.figure(figsize=(8, 4))
    plt.bar(names, vvals)
    plt.axhline(1.0, linestyle="--", linewidth=2, label="Exact speed = 1")
    plt.ylabel("Learned Characteristic Speed")
    plt.title("Learned Speed Across Test Cases")
    plt.xticks(rotation=25, ha="right")
    plt.grid(True, alpha=0.3, axis="y")
    plt.legend()
    plt.tight_layout()
    plt.savefig(fig_path, dpi=300)
    plt.close()

    print(f"Saved speed summary -> {fig_path}")

def save_summary_csv(summary, save_dir=FIG_DIR):
    csv_path = os.path.join(save_dir, "test_case_summary.csv")
    fieldnames = ["name", "x0", "nu", "rel_l2", "v_pred", "speed_error"]

    with open(csv_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in summary:
            writer.writerow(row)

    print(f"Saved CSV summary -> {csv_path}")

def visualize_rbf_centers_xt_learned_speed(model, test_cases, K=60, save_dir=FIG_DIR):
    """
    For the learned-characteristic model:
        s = (x - v(p)t) mod 1
    each center s_j lifts to
        x = (v(p)t + s_j) mod 1
    """
    model.eval()
    t_vals = np.linspace(0.0, 1.0, K)

    for name, x0_test, nu_test in test_cases:
        p_test = torch.tensor([[x0_test, nu_test]], dtype=torch.float32, device=device)
        xt_dummy = torch.zeros(1, 1, 2, dtype=torch.float32, device=device)

        with torch.no_grad():
            _, (g, s_centers, sigma, coeff, v_pred) = model(p_test, xt_dummy)

        g_np = g.cpu().numpy().reshape(-1)
        s_np = s_centers.cpu().numpy().reshape(-1)
        coeff_np = coeff.cpu().numpy().reshape(-1)
        sigma_np = sigma.cpu().numpy().reshape(-1)
        v_scalar = float(v_pred.item())

        weights = np.abs(g_np * coeff_np) + 1e-12

        X_pts, T_pts, W_pts, S_pts = [], [], [], []

        for s_j, w_j, sig_j in zip(s_np, weights, sigma_np):
            for t_k in t_vals:
                x_k = (v_scalar * t_k + s_j) % 1.0
                X_pts.append(x_k)
                T_pts.append(t_k)
                W_pts.append(w_j)
                S_pts.append(150.0 * sig_j)

        X_pts = np.array(X_pts)
        T_pts = np.array(T_pts)
        W_pts = np.array(W_pts)
        S_pts = np.array(S_pts)

        fig, ax = plt.subplots(figsize=(5.5, 5.2))
        sc = ax.scatter(X_pts, T_pts, c=W_pts, s=np.clip(S_pts, 8.0, 80.0), cmap="viridis", alpha=0.85)
        plt.colorbar(sc, ax=ax, label="|g_j c_j|")

        ax.scatter([x0_test], [0.0], s=90, marker="x", color="red", label="IC center")
        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        ax.set_xlabel("x")
        ax.set_ylabel("t")
        ax.set_title(f"Learned Characteristic Lift\n{name}, v_pred={v_scalar:.4f}")
        ax.legend(loc="upper right")

        save_path = os.path.join(save_dir, f"rbf_centers_xt_{name}.png")
        plt.tight_layout()
        plt.savefig(save_path, dpi=300)
        plt.close(fig)

        print(f"Saved RBF-characteristic plot -> {save_path}")

def run_full_meta_evaluation(model, history, test_cases, Nx=200, Nt=200, save_dir=FIG_DIR):
    plot_training_history(history, os.path.join(save_dir, "training_loss.png"))

    summary = plot_multicase_fields(model, test_cases, Nx=Nx, Nt=Nt, save_dir=save_dir)

    plot_time_slices(
        model,
        test_cases,
        t_slices=(0.0, 0.25, 0.50, 0.75, 1.0),
        Nx=400,
        save_dir=save_dir
    )

    plot_error_summary(summary, save_dir=save_dir)
    plot_speed_summary(summary, save_dir=save_dir)
    save_summary_csv(summary, save_dir=save_dir)
    visualize_rbf_centers_xt_learned_speed(model, test_cases, K=60, save_dir=save_dir)

    print("\nSummary of test cases:")
    for row in summary:
        print(
            f"{row['name']:22s} | "
            f"x0={row['x0']:.3f}, nu={row['nu']:.3f} | "
            f"relL2={row['rel_l2']:.3e} | "
            f"v_pred={row['v_pred']:.4f} | "
            f"|v-1|={row['speed_error']:.3e}"
        )

    return summary

# ============================================================
# Training
# ============================================================

def train_meta_advection(
    B_pde=4,
    N_int=256,
    N_ic=128,
    N_per=128,
    epochs=5000,
    lr=1e-3,
    print_every=100
):
    model = MetaKAPIRBF_Advection(M=32, hidden_meta=64, hidden_speed=32).to(device)
    optimizer = optim.Adam(model.parameters(), lr=lr)

    best_loss = float("inf")
    best_state = None

    history = {
        "epoch": [],
        "loss": [],
        "loss_pde": [],
        "loss_ic": [],
        "loss_per": [],
        "loss_sparse": [],
        "loss_speed": []
    }

    for ep in range(1, epochs + 1):
        model.train()
        optimizer.zero_grad()

        # Curriculum in nu
        if ep <= epochs // 2:
            nu_min_curr, nu_max_curr = nu_easy, nu_max
        else:
            nu_min_curr, nu_max_curr = nu_min, nu_max

        # Sample batch
        p_batch = sample_p_batch(B_pde, nu_range=(nu_min_curr, nu_max_curr))
        xt_int = sample_interior_points_batch(B_pde, N_int)
        xt_ic = sample_ic_points_batch(B_pde, N_ic)
        xtL, xtR = sample_periodic_points_batch(B_pde, N_per)

        # PDE loss
        res = advection_residual_batch(model, p_batch, xt_int)
        loss_pde = torch.mean(res ** 2)

        # Initial condition loss
        u_ic, _ = model(p_batch, xt_ic)
        x_ic = xt_ic[:, :, 0]
        x0 = p_batch[:, 0:1].expand_as(x_ic)
        nu = p_batch[:, 1:2].expand_as(x_ic)
        u_ic_true = periodic_gaussian(x_ic, x0, nu)
        loss_ic = torch.mean((u_ic - u_ic_true) ** 2)

        # Periodic boundary loss
        uL, _ = model(p_batch, xtL)
        uR, _ = model(p_batch, xtR)
        loss_per = torch.mean((uL - uR) ** 2)

        # Sparsity on gate amplitudes
        xt_aux = sample_interior_points_batch(B_pde, 8)
        _, (g, _, _, _, _) = model(p_batch, xt_aux)
        loss_sparse = 1e-4 * torch.mean(torch.abs(g))

        # Speed regularization
        xt_speed = sample_ic_points_batch(B_pde, 1)
        _, (_, _, _, _, v) = model(p_batch, xt_speed)
        loss_speed = 1e-3 * torch.mean((v - 1.0) ** 2)

        # Total loss
        loss = loss_pde + loss_ic + loss_per + loss_sparse + loss_speed

        loss.backward()
        optimizer.step()

        history["epoch"].append(ep)
        history["loss"].append(loss.item())
        history["loss_pde"].append(loss_pde.item())
        history["loss_ic"].append(loss_ic.item())
        history["loss_per"].append(loss_per.item())
        history["loss_sparse"].append(loss_sparse.item())
        history["loss_speed"].append(loss_speed.item())

        if loss.item() < best_loss:
            best_loss = loss.item()
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}

        if ep % print_every == 0 or ep == 1:
            print(
                f"Epoch {ep:4d} | "
                f"Loss {loss.item():.3e} | "
                f"PDE {loss_pde.item():.3e} | "
                f"IC {loss_ic.item():.3e} | "
                f"PER {loss_per.item():.3e} | "
                f"Speed {loss_speed.item():.3e}"
            )

        if device.type == "cuda":
            torch.cuda.empty_cache()

    if best_state is not None:
        model.load_state_dict(best_state)

    return model, history

# ============================================================
# Main
# ============================================================

if __name__ == "__main__":
    model, history = train_meta_advection(
        B_pde=4,
        N_int=256,
        N_ic=128,
        N_per=128,
        epochs=5000,
        lr=1e-3,
        print_every=100
    )

    torch.save(model.state_dict(), MODEL_PATH)
    print(f"Model saved to: {MODEL_PATH}")

    # Optional single snapshot
    plot_solution_snapshot(
        model,
        x0=0.45,
        nu=0.05,
        t_snap=0.50,
        nx=400,
        save_path=os.path.join(FIG_DIR, "snapshot_example.png")
    )

    # Reload model for evaluation
    loaded_model = MetaKAPIRBF_Advection(M=32, hidden_meta=64, hidden_speed=32).to(device)
    loaded_model.load_state_dict(torch.load(MODEL_PATH, map_location=device))
    loaded_model.eval()
    print("Reloaded model.")

    # Four test cases only
    test_cases = [
        ("Center (in-range)",     0.50, 0.07),
        ("Off-center (in-range)", 0.30, 0.09),
        ("Narrow (in-range)",     0.65, 0.04),
        ("Narrow (out-of-range)", 0.50, 0.02),
    ]

    summary = run_full_meta_evaluation(
        loaded_model,
        history,
        test_cases,
        Nx=200,
        Nt=200,
        save_dir=FIG_DIR
    )

    print(f"\nAll figures and CSV summary saved in: {FIG_DIR}")