# -*- coding: utf-8 -*-
"""TEST_CASE_03_META_CONV_DIFF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15fb-3u3ibFjE2tisAbCCPYp7vGOH0b0W
"""

# ------------------------------
# Cell 1: Imports + reproducibility + device + paths
# ------------------------------

import os
import random
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt

# Reproducibility
SEED = 1234
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Directories and model path
FIG_DIR = "figures_conv_diff"
os.makedirs(FIG_DIR, exist_ok=True)

MODEL_PATH = "meta_conv_diff_model.pt"

# Domain & parameter ranges
x_min, x_max = 0.0, 1.0
t_min, t_max = 0.0, 0.5

a_min, a_max = 0.5, 1.0      # advection speed range
nu_min, nu_max = 0.01, 0.05  # viscosity range

# Curriculum lower bound for "easy" phase:
# first half of training will use nu in [nu_easy, nu_max] (smoother problems),
# second half will use full [nu_min, nu_max].
nu_easy = 0.03

# ------------------------------
# Cell 2: Exact solution for advection–diffusion
#   u_t + a u_x = nu u_xx
#   u(x,t) = 1/sqrt(4t+1) * exp(-(x-0.2-a t)^2 / (nu(4t+1)))
# ------------------------------

def exact_advecdiff_torch(x, t, a, nu):
    """
    x, t, a, nu: torch tensors broadcastable to same shape
    returns u_exact as torch tensor
    """
    four_t1 = 4.0 * t + 1.0
    num = (x - 0.2 - a * t) ** 2
    den = nu * four_t1
    u = 1.0 / torch.sqrt(four_t1) * torch.exp(-num / den)
    return u

def exact_advecdiff_np(x, t, a, nu):
    """
    x, t: 2D meshgrid arrays (Nx, Nt)
    a, nu: scalars
    returns u_exact as (Nx, Nt) ndarray
    """
    four_t1 = 4.0 * t + 1.0
    num = (x - 0.2 - a * t) ** 2
    den = nu * four_t1
    u = 1.0 / np.sqrt(four_t1) * np.exp(-num / den)
    return u

# ------------------------------
# Cell 3: MetaDynamic KAPI–RBF model for advection–diffusion
# ------------------------------

class MetaDynamicKAPIRBF_AdvecDiff(nn.Module):
    def __init__(self, M=60):
        """
        M: number of RBF basis functions in x.
        Distributional parameters depend on (t,a,nu).
        """
        super().__init__()
        self.M = M

        # Gates g_j in (0,1) to prune or emphasize RBFs
        self.g_logits = nn.Parameter(torch.zeros(M))

        # Centers:
        # mu_j(t,a,nu) = tanh( mu0_j + vt_j t + va_j a + vnu_j nu )
        self.mu0   = nn.Parameter(torch.linspace(0.0, 1.0, M))
        self.v_t   = nn.Parameter(0.1 * torch.randn(M))
        self.v_a   = nn.Parameter(0.1 * torch.randn(M))
        self.v_nu  = nn.Parameter(0.1 * torch.randn(M))

        # Widths:
        # sigma_j(t,a,nu) = softplus(alpha0_j + st_j t + sa_j a + snu_j nu) + eps
        self.alpha0 = nn.Parameter(-1.0 * torch.ones(M))
        self.s_t    = nn.Parameter(0.05 * torch.randn(M))
        self.s_a    = nn.Parameter(0.05 * torch.randn(M))
        self.s_nu   = nn.Parameter(0.05 * torch.randn(M))

        # Amplitudes c_j (global across parameters)
        self.c = nn.Parameter(0.1 * torch.randn(M))

        self.eps = 1e-4

    def forward(self, xtanu):
        """
        xtanu: (N,4) tensor with columns (x,t,a,nu)
        Returns u(x,t,a,nu) as shape (N,)
        """
        x  = xtanu[:, 0:1]  # (N,1)
        t  = xtanu[:, 1:2]
        a  = xtanu[:, 2:3]
        nu = xtanu[:, 3:4]

        g = torch.sigmoid(self.g_logits)  # (M,)

        mu_tanu = torch.tanh(
            self.mu0.view(1, self.M)
            + self.v_t.view(1, self.M)  * t
            + self.v_a.view(1, self.M)  * a
            + self.v_nu.view(1, self.M) * nu
        )  # (N,M)

        sigma_tanu = torch.nn.functional.softplus(
            self.alpha0.view(1, self.M)
            + self.s_t.view(1, self.M)  * t
            + self.s_a.view(1, self.M)  * a
            + self.s_nu.view(1, self.M) * nu
        ) + self.eps  # (N,M)

        x_diff = x - mu_tanu
        r2 = (x_diff ** 2) / (2.0 * sigma_tanu ** 2)
        Phi = torch.exp(-r2)  # (N,M)

        coeff = g * self.c    # (M,)
        u = Phi @ coeff       # (N,)
        return u

# ------------------------------
# Cell 4: Sampling utilities for meta-training over (a,nu) WITH ν-range option
# ------------------------------

def sample_interior_points_meta(N_int, nu_range=None):
    """
    Interior points in [0,1] x [0,0.5] x [a_min,a_max] x [nu_low, nu_high].
    If nu_range is None, uses global (nu_min, nu_max).
    """
    if nu_range is None:
        nu_low, nu_high = nu_min, nu_max
    else:
        nu_low, nu_high = nu_range

    x  = x_min + (x_max - x_min) * torch.rand(N_int, 1)
    t  = t_min + (t_max - t_min) * torch.rand(N_int, 1)
    a  = a_min + (a_max - a_min) * torch.rand(N_int, 1)
    nu = nu_low + (nu_high - nu_low) * torch.rand(N_int, 1)

    return torch.cat([x, t, a, nu], dim=1).to(device)


def sample_ic_points_meta(N_ic, nu_range=None):
    """
    Initial condition points at t=0, with a ∈ [a_min,a_max], nu ∈ [nu_low, nu_high].
    """
    if nu_range is None:
        nu_low, nu_high = nu_min, nu_max
    else:
        nu_low, nu_high = nu_range

    x  = x_min + (x_max - x_min) * torch.rand(N_ic, 1)
    t  = torch.zeros(N_ic, 1)
    a  = a_min + (a_max - a_min) * torch.rand(N_ic, 1)
    nu = nu_low + (nu_high - nu_low) * torch.rand(N_ic, 1)

    return torch.cat([x, t, a, nu], dim=1).to(device)


def sample_bc_points_meta(N_bc, nu_range=None):
    """
    Boundary points at x=0 and x=1, t ∈ [0,0.5], a ∈ [a_min,a_max],
    nu ∈ [nu_low, nu_high].
    Returns xtanu_left, xtanu_right.
    """
    if nu_range is None:
        nu_low, nu_high = nu_min, nu_max
    else:
        nu_low, nu_high = nu_range

    t  = t_min + (t_max - t_min) * torch.rand(N_bc, 1)
    a  = a_min + (a_max - a_min) * torch.rand(N_bc, 1)
    nu = nu_low + (nu_high - nu_low) * torch.rand(N_bc, 1)

    xL = x_min * torch.ones(N_bc, 1)
    xR = x_max * torch.ones(N_bc, 1)

    xtanu_left  = torch.cat([xL, t, a, nu], dim=1)
    xtanu_right = torch.cat([xR, t, a, nu], dim=1)

    return xtanu_left.to(device), xtanu_right.to(device)

# ------------------------------
# Cell 5: PDE residual for meta advection–diffusion
#   u_t + a u_x - nu u_xx = 0
# ------------------------------

def advecdiff_residual_meta(model, xtanu_int):
    """
    xtanu_int: (N,4) interior points (x,t,a,nu).
    Returns residual r(x,t,a,nu) as (N,) tensor.
    """
    xtanu_int.requires_grad_(True)
    u = model(xtanu_int)  # (N,)

    grads = torch.autograd.grad(
        u,
        xtanu_int,
        grad_outputs=torch.ones_like(u),
        create_graph=True
    )[0]  # (N,4): [du/dx, du/dt, du/da, du/dnu]
    u_x = grads[:, 0]
    u_t = grads[:, 1]

    grads_x = torch.autograd.grad(
        u_x,
        xtanu_int,
        grad_outputs=torch.ones_like(u_x),
        create_graph=True
    )[0]
    u_xx = grads_x[:, 0]

    a_local  = xtanu_int[:, 2]
    nu_local = xtanu_int[:, 3]

    r = u_t + a_local * u_x - nu_local * u_xx
    return r

# ------------------------------
# Cell 6: Training loop with ν-curriculum + total-loss history + best checkpoint
# ------------------------------

def train_advecdiff_meta(
    N_int=2048,
    N_ic=512,
    N_bc=512,
    epochs=3000,
    lr=1e-3,
    M=100
):
    model = MetaDynamicKAPIRBF_AdvecDiff(M=M).to(device)
    optimizer = optim.Adam(model.parameters(), lr=lr)

    best_loss = float("inf")
    best_state = None

    history = {
        "epoch": [],
        "total_loss": []
    }

    for ep in range(1, epochs + 1):
        optimizer.zero_grad()

        # --------------------------
        # ν-curriculum (two phases)
        # --------------------------
        if ep <= epochs // 2:
            # Easy phase: only smoother problems (larger ν)
            nu_min_curr, nu_max_curr = nu_easy, nu_max
        else:
            # Full phase: entire training ν-range
            nu_min_curr, nu_max_curr = nu_min, nu_max

        # Sample interior / IC / BC points with current ν-range
        xtanu_int = sample_interior_points_meta(N_int, nu_range=(nu_min_curr, nu_max_curr))
        xtanu_ic  = sample_ic_points_meta(N_ic,       nu_range=(nu_min_curr, nu_max_curr))
        xtanu_L, xtanu_R = sample_bc_points_meta(N_bc, nu_range=(nu_min_curr, nu_max_curr))

        # ----- PDE loss -----
        r_int    = advecdiff_residual_meta(model, xtanu_int)
        loss_pde = torch.mean(r_int**2)

        # ----- IC loss (t=0, exact solution) -----
        u_ic   = model(xtanu_ic)
        x_ic   = xtanu_ic[:, 0:1]
        t_ic   = xtanu_ic[:, 1:2]
        a_ic   = xtanu_ic[:, 2:3]
        nu_ic  = xtanu_ic[:, 3:4]
        u0     = exact_advecdiff_torch(x_ic, t_ic, a_ic, nu_ic)
        loss_ic = torch.mean((u_ic - u0.squeeze())**2)

        # ----- BC loss at x=0 and x=1 (using exact solution) -----
        uL   = model(xtanu_L)
        xL   = xtanu_L[:, 0:1]
        tL   = xtanu_L[:, 1:2]
        aL   = xtanu_L[:, 2:3]
        nuL  = xtanu_L[:, 3:4]
        uL_exact = exact_advecdiff_torch(xL, tL, aL, nuL)

        uR   = model(xtanu_R)
        xR   = xtanu_R[:, 0:1]
        tR   = xtanu_R[:, 1:2]
        aR   = xtanu_R[:, 2:3]
        nuR  = xtanu_R[:, 3:4]
        uR_exact = exact_advecdiff_torch(xR, tR, aR, nuR)

        loss_bc = torch.mean((uL - uL_exact.squeeze())**2) + \
                  torch.mean((uR - uR_exact.squeeze())**2)

        # ----- Sparsity on gates -----
        g = torch.sigmoid(model.g_logits)
        loss_sparse = 1e-4 * torch.mean(torch.abs(g))

        # Total loss (same as before)
        loss = loss_pde + loss_ic + loss_bc + loss_sparse
        loss.backward()
        optimizer.step()

        # History
        history["epoch"].append(ep)
        history["total_loss"].append(loss.item())

        # Best checkpoint
        if loss.item() < best_loss:
            best_loss = loss.item()
            best_state = model.state_dict()

        if ep % 500 == 0:
            print(
                f"Epoch {ep:5d} | Total: {loss.item():.3e} | "
                f"PDE: {loss_pde.item():.3e}, IC: {loss_ic.item():.3e}, "
                f"BC: {loss_bc.item():.3e}, "
                f"nu_range=[{nu_min_curr:.3f}, {nu_max_curr:.3f}]"
            )

    print(f"\nBest training loss = {best_loss:.3e}")
    if best_state is not None:
        model.load_state_dict(best_state)

    return model, history

# ------------------------------
# Cell 7: Plot training curve (total loss)
# ------------------------------

def plot_training_curve(history):
    plt.figure(figsize=(6,4))
    plt.plot(history["epoch"], history["total_loss"])
    plt.yscale("log")
    plt.xlabel("Epoch")
    plt.ylabel("Total loss")
    plt.grid(True)
    plt.title("Meta conv–diff training loss")
    plt.tight_layout()
    plt.show()

# ------------------------------
# Cell 8: Evaluate on multiple (a,nu) cases + plots + save figures
#         3-row, 4-column multicase_fields.png template
# ------------------------------

def evaluate_and_plot_conv_diff(model, test_cases, Nx=200, Nt=200):
    """
    test_cases: list of (name, a_test, nu_test)

    Produces:
      - combined figure with:
            Row 1: Exact
            Row 2: Meta
            Row 3: Absolute error
        and columns = test cases
      - per-case figures (same as before)
      - printed relative L2 summary
    """
    num_tests = len(test_cases)

    x = np.linspace(x_min, x_max, Nx)
    t = np.linspace(t_min, t_max, Nt)
    Xg, Tg = np.meshgrid(x, t, indexing="ij")

    model.eval()

    summary = []
    exact_list = []
    pred_list = []
    err_list = []

    # -----------------------------------
    # First pass: evaluate all test cases
    # -----------------------------------
    for i, (name, a_test, nu_test) in enumerate(test_cases):
        print(f"\n=== Test case {i+1}/{num_tests}: {name} ===")
        print(f"  (a, nu) = ({a_test:.3f}, {nu_test:.3f})")

        # Exact
        U_exact = exact_advecdiff_np(Xg, Tg, a_test, nu_test)

        # Grid for model
        A_grid  = a_test * np.ones_like(Xg)
        Nu_grid = nu_test * np.ones_like(Xg)

        xtanu_grid = np.stack(
            [Xg.reshape(-1), Tg.reshape(-1), A_grid.reshape(-1), Nu_grid.reshape(-1)],
            axis=1
        )
        xtanu_grid_t = torch.tensor(xtanu_grid, dtype=torch.float32, device=device)

        with torch.no_grad():
            u_meta_flat = model(xtanu_grid_t)

        U_meta = u_meta_flat.cpu().numpy().reshape(Nx, Nt)

        err = np.abs(U_meta - U_exact)
        rel_L2 = np.linalg.norm(err.ravel()) / (np.linalg.norm(U_exact.ravel()) + 1e-14)

        summary.append({
            "name": name,
            "a": a_test,
            "nu": nu_test,
            "rel_l2": rel_L2
        })

        exact_list.append((name, a_test, nu_test, U_exact))
        pred_list.append((name, a_test, nu_test, U_meta))
        err_list.append((name, a_test, nu_test, err))

        print(f"  Relative L2 error = {rel_L2:.3e}")

        # -----------------------------------
        # Per-case figure (kept as before)
        # -----------------------------------
        single_path = os.path.join(FIG_DIR, f"meta_conv_diff_{name}.png")

        plt.figure(figsize=(12, 4))

        plt.subplot(1, 3, 1)
        plt.imshow(U_exact.T, extent=[x_min, x_max, t_min, t_max],
                   origin="lower", aspect="auto")
        plt.title("Exact")
        plt.xlabel("x")
        plt.ylabel("t")
        plt.colorbar()

        plt.subplot(1, 3, 2)
        plt.imshow(U_meta.T, extent=[x_min, x_max, t_min, t_max],
                   origin="lower", aspect="auto")
        plt.title("Meta")
        plt.xlabel("x")
        plt.ylabel("t")
        plt.colorbar()

        plt.subplot(1, 3, 3)
        plt.imshow(err.T, extent=[x_min, x_max, t_min, t_max],
                   origin="lower", aspect="auto")
        plt.title("Error")
        plt.xlabel("x")
        plt.ylabel("t")
        plt.colorbar()

        plt.tight_layout()
        plt.savefig(single_path, dpi=300)
        plt.close()
        print(f"  Saved per-case figure → {single_path}")

    # -----------------------------------
    # Shared color limits for combined plot
    # -----------------------------------
    all_sol_vals = np.concatenate(
        [U.ravel() for _, _, _, U in exact_list + pred_list]
    )
    sol_vmin = np.min(all_sol_vals)
    sol_vmax = np.max(all_sol_vals)

    all_err_vals = np.concatenate(
        [E.ravel() for _, _, _, E in err_list]
    )
    err_vmin = 0.0
    err_vmax = np.max(all_err_vals)

    # -----------------------------------
    # Combined 3-row, num_tests-column plot
    # -----------------------------------
    fig, axs = plt.subplots(
        3, num_tests,
        figsize=(4.4 * num_tests, 9.6),
        constrained_layout=True
    )

    if num_tests == 1:
        axs = axs.reshape(3, 1)

    im_sol = None
    im_err = None

    for j in range(num_tests):
        name, a_test, nu_test, U_exact = exact_list[j]
        _, _, _, U_meta = pred_list[j]
        _, _, _, err = err_list[j]

        # Row 1: Exact
        ax = axs[0, j]
        im_sol = ax.imshow(
            U_exact.T,
            origin="lower",
            extent=[x_min, x_max, t_min, t_max],
            aspect="auto",
            vmin=sol_vmin,
            vmax=sol_vmax
        )
        ax.set_title(rf"$(a,\nu)=({a_test:.2f},{nu_test:.3f})$", fontsize=14)
        ax.set_xlabel("x")
        if j == 0:
            ax.set_ylabel("Exact", fontsize=13)

        # Row 2: Meta
        ax = axs[1, j]
        ax.imshow(
            U_meta.T,
            origin="lower",
            extent=[x_min, x_max, t_min, t_max],
            aspect="auto",
            vmin=sol_vmin,
            vmax=sol_vmax
        )
        ax.set_xlabel("x")
        if j == 0:
            ax.set_ylabel("KAPI", fontsize=13)

        # Row 3: Error
        ax = axs[2, j]
        im_err = ax.imshow(
            err.T,
            origin="lower",
            extent=[x_min, x_max, t_min, t_max],
            aspect="auto",
            vmin=err_vmin,
            vmax=err_vmax
        )
        ax.set_xlabel("x")
        if j == 0:
            ax.set_ylabel(r"$|u_{\mathrm{KAPI}}-u_{\mathrm{Exact}}|$", fontsize=13)

    # Shared colorbars
    cbar1 = fig.colorbar(im_sol, ax=axs[0:2, :], shrink=0.95, location="right")
    cbar1.set_label("Solution value", fontsize=12)

    cbar2 = fig.colorbar(im_err, ax=axs[2, :], shrink=0.95, location="right")
    cbar2.set_label("Absolute error", fontsize=12)

    # Training range annotation
    training_text = (
        rf"Training ranges: "
        rf"$a \in [{a_min:.2f},{a_max:.2f}]$, "
        rf"$\nu \in [{nu_min:.3f},{nu_max:.3f}]$"
    )

    fig.text(
        0.5, -0.02,
        training_text,
        ha="center",
        va="top",
        fontsize=13
    )

    combined_path = os.path.join(FIG_DIR, "multicase_fields.png")
    fig.savefig(combined_path, dpi=300, bbox_inches="tight")
    plt.close(fig)

    print(f"\nSaved combined figure → {combined_path}")

    print("\nSummary of relative L2 errors:")
    for row in summary:
        print(f"  {row['name']:25s}: {row['rel_l2']:.3e}")

# ------------------------------
# Cell 9: RBF centers in (x,t)-plane
# ------------------------------

def visualize_rbf_centers_xt_conv_diff(model, test_cases, K=50):
    """
    Visualize RBF centers mu_j(t,a,nu) in (x,t)-plane for each test (a,nu).
    For each center j and time sample t_k, we plot (mu_j(t_k), t_k),
    colored by |g_j * c_j|.
    """
    model.eval()

    for name, a_test, nu_test in test_cases:
        print(f"\nRBF center visualization in (x,t) for: {name}")

        # Time samples
        t_vals = torch.linspace(t_min, t_max, K, device=device).view(K, 1)
        a_vals = torch.full((K, 1), a_test, device=device)
        nu_vals = torch.full((K, 1), nu_test, device=device)
        x_dummy = torch.zeros(K, 1, device=device)  # not used in mu formula

        # We recompute mu_tanu exactly as in forward, but for multiple t
        with torch.no_grad():
            mu_tanu = torch.tanh(
                model.mu0.view(1, model.M)
                + model.v_t.view(1, model.M)  * t_vals
                + model.v_a.view(1, model.M)  * a_vals
                + model.v_nu.view(1, model.M) * nu_vals
            )  # (K, M)

            g = torch.sigmoid(model.g_logits)      # (M,)
            c = model.c                            # (M,)
            w = torch.abs(g * c) + 1e-12           # (M,)

        mu_np = mu_tanu.cpu().numpy()   # (K,M)
        t_np  = t_vals.cpu().numpy()    # (K,1)
        w_np  = w.cpu().numpy()         # (M,)

        # Build point cloud in (x,t)
        X_pts = []
        T_pts = []
        W_pts = []

        for j in range(model.M):
            for k in range(K):
                X_pts.append(mu_np[k, j])
                T_pts.append(t_np[k, 0])
                W_pts.append(w_np[j])

        X_pts = np.array(X_pts)
        T_pts = np.array(T_pts)
        W_pts = np.array(W_pts)

        fig, ax = plt.subplots(figsize=(5, 5))
        sc = ax.scatter(X_pts, T_pts, c=W_pts, s=12, cmap="viridis")
        plt.colorbar(sc, ax=ax, label="|g * c|")

        ax.set_title(f"RBF centers in (x,t)\n{name}", fontsize=12)
        ax.set_xlabel("x")
        ax.set_ylabel("t")
        ax.set_xlim(x_min - 0.1, x_max + 0.1)
        ax.set_ylim(t_min, t_max)

        # Mark initial Gaussian center at t=0, x=0.2
        ax.scatter([0.2], [0.0], color="red", marker="x", s=80, label="IC center")
        ax.legend(loc="upper right")

        centers_path = os.path.join(FIG_DIR, f"rbf_centers_xt_{name}.png")
        plt.tight_layout()
        plt.savefig(centers_path, dpi=300)
        plt.show()

        print(f"Saved RBF centers (x,t) figure → {centers_path}")

# ------------------------------
# Cell 10: Train → Save → Reload → Evaluate → RBF centers
# ------------------------------

# 1) Train meta-model
model, history = train_advecdiff_meta(
    N_int=2048,
    N_ic=512,
    N_bc=512,
    epochs=3000,   # reduce for quick tests
    lr=1e-3,
    M=100
)

# 2) Save best model
torch.save(model.state_dict(), MODEL_PATH)
print(f"\nSaved best conv–diff meta-model to: {MODEL_PATH}")

# 3) Plot training curve
plot_training_curve(history)

# 4) Reload model for evaluation
loaded_model = MetaDynamicKAPIRBF_AdvecDiff(M=100).to(device)
state_dict = torch.load(MODEL_PATH, map_location=device)
loaded_model.load_state_dict(state_dict)
loaded_model.eval()
print("Reloaded model from disk.")

# 5) Define interesting test cases in (a, nu)
test_cases = [
    ("mid_range",           0.75, 0.03),   # middle of both ranges
    ("low_a_high_nu",       0.55, 0.045),  # slower advection, more diffusion
    ("high_a_low_nu",       0.95, 0.015),  # faster advection, less diffusion
    ("nu_out_of_range_low", 0.75, 0.008),  # smaller nu than trained (harder)
]


# 6) Evaluate & plot solutions
evaluate_and_plot_conv_diff(loaded_model, test_cases, Nx=200, Nt=200)

# 7) Visualize RBF centers in (x,t)-plane
visualize_rbf_centers_xt_conv_diff(loaded_model, test_cases, K=50)